server:
  port: 8085

spring:
  application:
    name: channel

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??

  profiles:
    include: oauth

jwt:
  secret: /vUwAz/Vx78zX5/E4v6kjfbyoTRpYtOK2WT9rYcXeNPzDMuv1BlehYL113paVVYvUTyUIYg3kSZglWjEAJxgMw==

jasypt:
  encryptor:
    key: 263d0bdda7c420e6

springdoc:
  api-docs:
    path: /channel-api/v3/api-docs
  swagger-ui:
    path: /channel-api/v3/swagger-ui.html

---
spring:
  profiles:
    active: dev, prod